services:
  - type: web
    name: damodar-grocery-store
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: damodar-grocery-db
          property: connectionString

databases:
  - name: damodar-grocery-db
    plan: free
